name: showcase
description: "Showcase App"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.8.0+1
  get_it: ^8.0.3
  injectable: ^2.5.0
  pretty_dio_logger: ^1.4.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.5.1
  freezed: ^3.0.6
  injectable_generator: ^2.4.1
  json_serializable: ^6.9.5
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
